### ISSUE TITLE
data-* warning irrelevant for internal properties

### ISSUE THREAD

**Issue by reliable-casey** [Netflix/x-element#74]
Given that `internal` properties may not be attribute bound or reflected, it probably makes sense to relax this warning in this case.

**Comment by theengineear** [comment]
I wrote up a long response, but... perhaps a return question would be more helpful.

Rather than "relax this warning", do you really mean "should internal properties register a related attribute at all"?

I'm less-inclined to do the former, but a broader change to stop registering attributes for internal properties would potentially be more reasonable.

(For context, _all_ properties are currently associated with an attribute — even internal ones. That's how we are able to throw an error if an integrator attempts to update an internal property through an attribute.)

Thoughts @klebba?

**Comment by reliable-casey** [comment]
Yeah, that's a great point — I would agree that `internal` properties should not register a related attribute at all
