### ISSUE TITLE
change the default behavior to not reflect properties as attributes

### ISSUE THREAD

**Issue by codeStryke** [Netflix/x-element#80]
opening up an issue to discuss changing the default behavior to not automatically reflect every property as an attribute. Instead, we can rely on the `attribute` field of a `property` that we want observed. This change will makes the interface more explicit, avoid shadowing attributes like `id` or `data-*`.
@theengineear @klebba

**Comment by klebba** [comment]
@codeStryke only scalar values may be reflected as attributes; boolean, number, string — and the behavior is not automatic. The developer must opt in using `reflect: true` in their property definition.

Our philosophy on overloading attribute names is that the library should not get in the way of the developer. The developer is thus expected to understand the way the browser interacts with attribute names they choose.

For example what if I actually do want to bind `id` or `tabindex` or `title` — all are native [global attributes](https://www.w3schools.com/tags/ref_standardattributes.asp) with special user agent behavior — the library can populate them for me using my property declarations. Otherwise I have to rewrite this functionality myself to populate them (yuck). IMO we don't want to be in the business of determining which attribute names to disallow; the developer should make this determination

**Comment by klebba** [comment]
Also see #77

**Comment by codeStryke** [comment]
The problem is the library makes the assumption that any custom property defined by the component author needs to be available as an attribute as well. Instead the author should be free to decide what the interface is, explicitly.

**Comment by reliable-casey** [comment]
Can you explain the use case or issue you're working around?

**Comment by codeStryke** [comment]
I have a lot of properties in the interface with names like `dataQuery`, `dataQueryVersion`or `dataQuery<xyz>`. Then the console is flooded with messages like these
![image](https://user-images.githubusercontent.com/5248016/108612373-243d7800-739d-11eb-87d9-5589eedeb283.png)

**Comment by klebba** [comment]
@codeStryke what if the warning was just removed?

**Comment by codeStryke** [comment]
@klebba the warnings may be potentially useful to resolve subtle hard to debug issues (not encountered any so far in 2yrs of using the framework). 
Isn't the root of the issue the automatic kebab case conversion (of property names) + automatic observing off attribute changes?

**Comment by klebba** [comment]
In theory these kind of warnings sounded useful but in practice I find them to be in my way, and it sounds like the same is true in your case. The potential impact of your recommendation is far reaching; perhaps you could pull some stats from the roster of `x-element` features you maintain to characterize this impact in more detail but my intuition here is that this change would have me adding this flag to nearly every property definition. Also I'm not convinced that this suggestion wouldn't be confusing in the other direction:

```
...
{
  dataFoo: {
    type: String,
  },
},
...
<my-foo data-foo="${bar}"></my-foo>
```
If this attribute has no relationship with the declared property by default then it requires the developer to constantly opt into one of the library's main functions. Further if there is no relationship with the attribute the inner template will not render automagically when changes to the attribute are made. This is probably not what you want.

It may be reasonable to set a global flag to flip `x-element` into strict mode for this type of feedback but I would prefer to remove these warnings from library entirely. We could perhaps include a static analysis tool in the future to detect these issues and decouple this from library itself.

Also worth noting that there are many other potentially subtle interactions with browser behavior that are not guarded by any warnings, e.g. `draggable` — IMO the developer will always need to understand the implications of their name choices in the browser environment — there are many cases to be sensitive to like `prototype` `super` `window` etc etc etc. For the library to provide more comprehensive bumper lanes the detection code would quickly eclipse the functional code and require constant maintenance.

**Comment by codeStryke** [comment]
Makes sense. How about adopting something that LitElement does which is 
```
...
{
  dataFoo: {
    type: String,
  },
},
...
<my-foo datafoo="${bar}"></my-foo>
```
the `property` name is lowercased and not kebab cased.

I still feel that the root of the issue lies in the decision to kebab case vs lowercase. Thoughts?

**Comment by klebba** [comment]
Attributes are case insensitive, so the only options are to use hyphens as word delimiters or nothing at all. There is a [bit of both](https://www.w3schools.com/tags/ref_attributes.asp) in the set of standard HTML attributes and it's true that non-delimited attribute names are in the majority.

When we were initially prototyping this functionality we chose hyphenation to align with the Polymer library, which is the precursor to LitElement. Because camel cased property names use uppers to demarcate new words we also felt it was appropriate to match this in the derived attribute naming scheme by using delimiters there too. The result is more readable, but I'll admit it's a matter of preference. Additionally, attribute names are frequently used for CSS styling selectors — in CSS [hyphen casing](https://www.w3schools.com/cssref/) is far more prevalent, so your custom attributes don't feel out of place:

```css
...
my-custom-element[my-custom-attribute] {
  font-color: #f00;
}
```

Ultimately it seems like you're advocating for `x-element` to mirror the behavior of LitElement, and provide more control over custom attribute naming and reflection: https://lit-element.polymer-project.org/guide/properties#observed-attributes

However we specifically chose not to include configuration of attribute names in `x-element` for the sake of consistency and predictability. This also helps the library remain dead simple. You could always lowercase your property definition to accomplish what you want:

```
{
  datafoo: {
    type: String,
  },
},
...
<my-foo datafoo="${bar}"></my-foo>
```

But I would guess you're probably not in control of the camel cased property names in the JavaScript objects you are data binding. There may not be [any answer](https://martinfowler.com/bliki/TwoHardThings.html) that satisfies everyone...

**Comment by codeStryke** [comment]
Not anymore, removing the nudges is a good middle ground.

**Comment by klebba** [comment]
Ok great, closing the issue. Thanks!

**Comment by theengineear** [comment]
☝️ — Just following along. I'll close this down for us 👌
