### ISSUE TITLE
Allow extending `observedAttributes`.

### ISSUE THREAD

**Issue by theengineear** [Netflix/x-element#84]
Super minor change, but we expect all `observedAttributes` to come from our statically-declared `properties`. Instead, we should assume that authors may want to observe additional attributes beyond what they declared in the properties block. That is, we should allow this:

```
static get observedAttributes() {
  return [...super.observedAttributes, 'some-other-thing'];
}
```

**Comment by klebba** [comment]
@theengineear why would they be disinclined to declare this in the property block? Can you include a material example? Not resisting the change per se but I don't yet follow when/why I would use this

**Comment by klebba** [comment]
Wew, I can't believe I left this hanging since May. I will admit I don't fully grok the technical problem, and a code level example would help, but I don't want to level more burden contextualizing this. You had me at "I can add behavior to the other standard methods, why not `observedAttributes`" — philosophically this is misaligned with the project.
